## dev环境使用是配置
server:
  port: 8081
  context-path: /dzr

spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/dzr?useUnicode=true&characterEncoding=UTF-8
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver








