## dev环境使用是配置
server:
  port: 8081
  context-path: /chao


spring:
  ## thymeleaf的默认配置
  #spring.thymeleaf.prefix=classpath:/templates/
  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.mode=HTML5
  #spring.thymeleaf.encoding=UTF-8
  #spring.thymeleaf.content-type=text/html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false
  ## freemarker
  #spring.freemarker.allow-request-override=false
  #spring.freemarker.cache=true
  #spring.freemarker.check-template-location=true
  #spring.freemarker.charset=UTF-8
  #spring.freemarker.content-type=text/html
  #spring.freemarker.expose-request-attributes=false
  #spring.freemarker.expose-session-attributes=false
  #spring.freemarker.expose-spring-macro-helpers=false
  freemarker:
    charset: UTF-8
    content-type: text/html
    cache: false
    suffix: .html



mouth: 11
day: 12
##配置使用配置
time: 2017-${mouth}-${day}

##对象配置
person:
  name: 王海潮
  age: 22
  address: 小上海






url:
  security:
    ## 拦截需要验证的url,数组的形式
    ## authenticated: /private/**,/framework/**
    authenticated: /private/**


qingyun:
  APP_KEY: DDEZFCHJEZTNNLFHGFPG
  ACCESS_KEY: Hehu9aK5gXDc2hsSCzsdEqnW668lMpPI6TxZKaxV
  ZONE: sh1a
  CMD: /home/qsctl
#  CMD: /Users/sgx/Downloads/qsctl







