## dev环境使用是配置
server:
  port: 8081
  context-path: /chao

spring:
   ## freemarker
   #spring.freemarker.allow-request-override=false
   #spring.freemarker.cache=true
   #spring.freemarker.check-template-location=true
   #spring.freemarker.charset=UTF-8
   #spring.freemarker.content-type=text/html
   #spring.freemarker.expose-request-attributes=false
   #spring.freemarker.expose-session-attributes=false
   #spring.freemarker.expose-spring-macro-helpers=false
     freemarker:
       charset: UTF-8
       content-type: text/html
       cache: false
       suffix: .html

##对象配置
person:
  name: 王海潮
  age: 22
  address: 小上海







